import type { TransformedToken, FormatFnArguments } from 'style-dictionary/types';

/* =========================================
   Android XML Formats
   Generates Android resource XML files
   for colors.xml and dimens.xml.
   ========================================= */

/** Converts a token name to Android resource naming (snake_case) */
function toAndroidName(name: string): string {
  return name
    .replace(/\./g, '_')
    .replace(/([a-z])([A-Z])/g, '$1_$2')
    .replace(/-/g, '_')
    .toLowerCase();
}

/**
 * Converts a hex color to Android's ARGB 8-digit hex format.
 * Android uses #AARRGGBB ordering.
 */
function toAndroidColor(value: string): string {
  // Already 8-digit with alpha
  if (/^#[A-Fa-f0-9]{8}$/.test(value)) {
    return value.toUpperCase();
  }
  // 6-digit hex → add FF alpha prefix
  if (/^#[A-Fa-f0-9]{6}$/.test(value)) {
    return `#FF${value.slice(1)}`.toUpperCase();
  }
  // 3-digit hex → expand and add alpha
  if (/^#[A-Fa-f0-9]{3}$/.test(value)) {
    const [, r, g, b] = value.split('');
    return `#FF${r}${r}${g}${g}${b}${b}`.toUpperCase();
  }
  return value;
}

export function androidColorsFormat({ dictionary, file }: FormatFnArguments) {
  const tokens = dictionary.allTokens.filter(
    (t: TransformedToken) => t.$type === 'color'
  );

  const header = `<?xml version="1.0" encoding="utf-8"?>\n<!-- ${file.destination} - Generated by theming-engine -->\n`;

  const resources = tokens
    .map((token: TransformedToken) => {
      const name = toAndroidName(token.name);
      const val = token.$value ?? token.value;
      const value = toAndroidColor(String(val));
      return `    <color name="${name}">${value}</color>`;
    })
    .join('\n');

  return `${header}<resources>\n${resources}\n</resources>\n`;
}

export function androidDimensFormat({ dictionary, file }: FormatFnArguments) {
  const tokens = dictionary.allTokens.filter(
    (t: TransformedToken) => t.$type === 'dimension'
  );

  const header = `<?xml version="1.0" encoding="utf-8"?>\n<!-- ${file.destination} - Generated by theming-engine -->\n`;

  const resources = tokens
    .map((token: TransformedToken) => {
      const name = toAndroidName(token.name);
      // Convert px to dp for Android
      const val = token.$value ?? token.value;
      const value = String(val).replace('px', 'dp');
      return `    <dimen name="${name}">${value}</dimen>`;
    })
    .join('\n');

  return `${header}<resources>\n${resources}\n</resources>\n`;
}

export function androidFontDimensFormat({ dictionary, file }: FormatFnArguments) {
  const tokens = dictionary.allTokens.filter(
    (t: TransformedToken) =>
      t.$type === 'dimension' && (t.path.includes('fontSize') || t.path.includes('letterSpacing'))
  );

  const header = `<?xml version="1.0" encoding="utf-8"?>\n<!-- ${file.destination} - Generated by theming-engine -->\n`;

  const resources = tokens
    .map((token: TransformedToken) => {
      const name = toAndroidName(token.name);
      const val = token.$value ?? token.value;
      const value = String(val).replace('px', 'sp');
      return `    <dimen name="${name}">${value}</dimen>`;
    })
    .join('\n');

  return `${header}<resources>\n${resources}\n</resources>\n`;
}

