import type { TransformedToken, FormatFnArguments } from 'style-dictionary/types';

/* =========================================
   Core CSS Format
   Generates core/base CSS variables under
   :root and appends global keyframes.
   ========================================= */

export function coreCssFormat({ dictionary, file }: FormatFnArguments) {
  const tokens = dictionary.allTokens;
  const variables = tokens
    .map((token: TransformedToken) => {
      const name = token.name.replace(/\./g, '-');
      const val = token.$value ?? token.value;
      return `  --${name}: ${val};`;
    })
    .join('\n');

  const keyframes = `
@keyframes fade-in {
  from { opacity: 0; }
  to { opacity: 1; }
}

@keyframes slide-up {
  from {
    opacity: 0;
    transform: translateY(12px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

@keyframes scale-in {
  from {
    opacity: 0;
    transform: scale(0.97);
  }
  to {
    opacity: 1;
    transform: scale(1);
  }
}

@keyframes shimmer {
  0% { background-position: -200% 0; }
  100% { background-position: 200% 0; }
}

@keyframes slide-down {
  from {
    opacity: 0;
    transform: translateY(-10px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

@keyframes rotation {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}
`;

  const header = `/**\n * ${file.destination}\n * Generated by theming-engine — Do not edit directly\n */\n`;

  return `${header}:root {\n${variables}\n}\n${keyframes}`;
}
