import type { TransformedToken, FormatFnArguments } from 'style-dictionary/types';

/* =========================================
   JS/TS Module Format
   Generates a typed TypeScript module
   exporting all tokens as a nested object.
   ========================================= */

export function jsModuleFormat({ dictionary, file }: FormatFnArguments) {
  const tokens = dictionary.allTokens;
  if (tokens.length === 0) return '';

  const header = `/**\n * ${file.destination}\n * Generated by theming-engine — Do not edit directly\n */\n`;

  // Build a flat map for simple consumption
  const flatEntries = tokens
    .map((token: TransformedToken) => {
      const name = token.name.replace(/\./g, '-');
      const val = token.$value ?? token.value;
      const value = typeof val === 'number' ? val : `'${val}'`;
      return `  '${name}': ${value},`;
    })
    .join('\n');

  // Build a nested object
  const nested: Record<string, unknown> = {};
  for (const token of tokens) {
    const parts = token.path;
    let current: Record<string, unknown> = nested;

    for (let i = 0; i < parts.length - 1; i++) {
      const part = parts[i]!;
      if (!(part in current)) {
        current[part] = {};
      }
      current = current[part] as Record<string, unknown>;
    }

    current[parts[parts.length - 1]!] = token.$value ?? token.value;
  }


  return `${header}
export const tokens = {
${flatEntries}
} as const;

export type TokenName = keyof typeof tokens;

export const tokenTree = ${JSON.stringify(nested, null, 2)} as const;

export default tokens;
`;
}
