import type { TransformedToken, FormatFnArguments } from 'style-dictionary/types';
import { createPropertyFormatter } from 'style-dictionary/utils';

/* =========================================
   Themed SCSS Format
   Generates SCSS $variable definitions and
   theme-scoped mixins.
   ========================================= */

/**
 * Extracts theme name and appearance from token file path.
 */
function parseThemeFromPath(filePath: string): { theme: string; appearance: string } | null {
  const match = filePath.match(/brands\/([^/]+)\/(light|dark)/);
  if (!match) return null;
  return { theme: match[1]!, appearance: match[2]! };
}

function parseThemeFromDestination(destination: string): { theme: string; appearance: string } | null {
  const match = destination.match(/themes\/_?(.+)-(light|dark)\.(css|scss)$/);
  if (!match) return null;
  return { theme: match[1]!, appearance: match[2]! };
}

export function themedScssFormat({ dictionary, file, options }: FormatFnArguments) {
  const tokens = dictionary.allTokens;
  if (tokens.length === 0) return '';

  const themeInfo =
    parseThemeFromDestination(file.destination) ??
    parseThemeFromPath(tokens[0]!.filePath);

  const header = `//\n// ${file.destination}\n// Generated by theming-engine — Do not edit directly\n//\n`;

  if (themeInfo) {
    // Theme-scoped: generate a mixin and CSS variable block
    const mixinName = `theme-${themeInfo.theme}-${themeInfo.appearance}`;
    const selector = `[data-theme="${themeInfo.theme}"][data-appearance="${themeInfo.appearance}"]`;

    const scssVars = tokens
      .map((token: TransformedToken) => {
        const name = token.name.replace(/\./g, '-');
        const val = token.$value ?? token.value;
        return `  $${name}: ${val} !default;`;
      })
      .join('\n');

    const cssVars = tokens
      .map((token: TransformedToken) => {
        const name = token.name.replace(/\./g, '-');
        return `    --${name}: #{$${name}};`;
      })
      .join('\n');

    return `${header}\n${scssVars}\n\n@mixin ${mixinName} {\n${cssVars}\n}\n\n${selector} {\n  @include ${mixinName};\n}\n`;
  } else {
    // Core or component tokens: plain SCSS variables with reference support
    const formatProperty = createPropertyFormatter({
      outputReferences: options?.outputReferences,
      dictionary,
      format: 'sass',
      usesDtcg: options?.usesDtcg ?? true,
      themeable: true,
    });
    const variables = tokens.map(formatProperty).join('\n');

    return `${header}\n${variables}\n`;
  }
}

