import type { TransformedToken, FormatFnArguments } from 'style-dictionary/types';

/* =========================================
   Themed CSS Format
   Generates theme-scoped CSS variables using
   [data-theme][data-appearance] selectors.
   ========================================= */

/**
 * Extracts theme name and appearance from token file path.
 * Expected path pattern: .../brands/{theme}/{appearance}.ts
 */
function parseThemeFromPath(filePath: string): { theme: string; appearance: string } | null {
  const match = filePath.match(/brands\/([^/]+)\/(light|dark)/);
  if (!match) return null;
  return { theme: match[1]!, appearance: match[2]! };
}

/**
 * Extracts theme name and appearance from build output filename.
 * Expected pattern: themes/{theme}-{appearance}.css
 */
function parseThemeFromDestination(destination: string): { theme: string; appearance: string } | null {
  const match = destination.match(/themes\/_?(.+)-(light|dark)\.(css|scss)$/);
  if (!match) return null;
  return { theme: match[1]!, appearance: match[2]! };
}

export function themedCssFormat({ dictionary, file }: FormatFnArguments) {
  const tokens = dictionary.allTokens;
  if (tokens.length === 0) return '';

  const themeInfo =
    parseThemeFromDestination(file.destination) ??
    parseThemeFromPath(tokens[0]!.filePath);

  // Build selector
  let selector: string;
  if (themeInfo) {
    selector = `[data-theme="${themeInfo.theme}"][data-appearance="${themeInfo.appearance}"]`;
  } else {
    selector = ':root';
  }

  // Generate CSS variables
  const variables = tokens
    .map((token: TransformedToken) => {
      const name = token.name.replace(/\./g, '-');
      const val = token.$value ?? token.value;
      return `  --${name}: ${val};`;
    })
    .join('\n');


  const header = `/**\n * ${file.destination}\n * Generated by theming-engine — Do not edit directly\n */\n`;

  return `${header}${selector} {\n${variables}\n}\n`;
}

